AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vehicle_price_prediction
  Sample SAM Template for vehicle_price_prediction

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
    MemorySize: 2048

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
      
Resources:
  ModelInferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: model_inference/
      Handler: app.lambda_handler
      Runtime: python3.9
      EphemeralStorage: 
        Size: 2048
      Policies:
        - S3ReadPolicy: { "BucketName": "hr-s3-itec" }
      Architectures:
      - x86_64
      Events:
        API:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /inference
            Method: post

    Metadata:
          Dockerfile: Dockerfile
          DockerContext: ./model_inference
          DockerTag: python3.9-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  API:
    Description: API Gateway endpoint URL for Prod stage for ModelInference function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ModelInferenceFunction:
    Description: Model Inference Lambda Function ARN
    Value: !GetAtt ModelInferenceFunction.Arn
  ModelInferenceFunctionIamRole:
    Description: Implicit IAM Role created for ModelInference function
    Value: !GetAtt ModelInferenceFunctionRole.Arn
